### PR TITLE
CARE-487 Allow .NET 8 App Services and Functions

### PR DESCRIPTION
**Pull request by safakgur**

### CODE REVIEW

**Comment by kunalgujar** [comment]
Nice one - thanks @safakgur

**Comment by safakgur** [comment]
Argh - it seems to fail at everything:

image

I knew I should've installed Go and run the tests properly rather than copying what @fabienmazieres did at #13 and crossing my fingers.

**Comment by fabienmazieres** [comment]
@samuelepecetto When I last made changes I did not even had some many success in the tests so you are good to go.
Changes will not be immediately available into Octopus, we have a few things to do in the background to make it available.

**Review by fabienmazieres — APPROVED** [review]

**Review by fabienmazieres — COMMENTED** [review]
We should not bring in changes into newday provider but update the official provider instead to force people to move off the custom provider

**Pull request closed without merging**
